import { type Ability } from '~/types/types';
import { AbilityTypes, DefaultAbilityImage } from '~/constants/constants';
import { EffectedAbility } from '~/utils/utils';
import { Effects } from '~/constants/effects';

export interface InFightAbility extends EffectedAbility {
  reloadLeft?: number;
}

export const Abilities: { [key: string]: Ability } = {
  default: {
    id: String(),
    name: 'Кулаки',
    description: 'Удар кулаком наносит 0 или 1 урона с 50% шансом одному врагу',
    type: AbilityTypes.other,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [],
    effectsForMe: [],
    damage: 0,
    targetsCount: 1,
    heal: 0,
    reload: 1,
    chances: [
      {
        damage: 1,
        probability: 0.5,
      },
    ],
  },
  healPotion: {
    id: String(),
    name: 'Лечение',
    description: 'Восстанавливает 3 едницы здоровья',
    type: AbilityTypes.potion,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [],
    effectsForMe: [],
    damage: 0,
    targetsCount: 0,
    heal: 3,
    reload: 5,
    chances: [],
  },
  swordStorm: {
    id: String(),
    name: 'Меч "Грань Шторма"',
    description: '15 урона. С шансом 50% накладывает командное кровотечение на всех игроков кроме атакуемого',
    type: AbilityTypes.sword,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [],
    effectsForMe: [],
    damage: 15,
    targetsCount: 1,
    heal: 0,
    reload: 3,
    chances: [
      {
        effectsToTargets: [Effects.teamBleeding_2.id],
        probability: 0.5,
      },
    ],
  },
  daggerNightCardinal: {
    id: String(),
    name: 'Кинжал "Ночной кардинал"',
    description: 'Крадет по 2 единицы здоровья у противников',
    type: AbilityTypes.dagger,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [Effects.bleeding_2.id],
    effectsForMe: [],
    damage: 8,
    targetsCount: 2,
    heal: 0,
    reload: 3,
    chances: [],
  },
  swordAlchemy: {
    id: String(),
    name: 'Сабля алхимика',
    description: 'Дает кровотечение - противник теряет по 2 здоровья каждый его ход',
    type: AbilityTypes.sword,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [Effects.bleeding_2.id],
    effectsForMe: [],
    damage: 6,
    targetsCount: 1,
    heal: 0,
    reload: 3,
    chances: [],
  },
  pistolDeathBreath: {
    id: String(),
    name: 'Выстрел "Дыхания Смерти"',
    description: 'Выстрел проходит сквозь броню и оставляет сильно кровоточащие раны, которые наносят 4 урона каждый ход',
    type: AbilityTypes.sword,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [Effects.bleeding_4.id],
    effectsForMe: [],
    piercingDamage: 6,
    damage: 0,
    targetsCount: 1,
    heal: 0,
    reload: 4,
    chances: [],
  },
  powerDoubleDamage: {
    id: String(),
    name: 'Двойной урон',
    description:
      'Сразу после использования этой способности можно разыграть ещё одну, урон которой будет увеличен в 2 раза',
    type: AbilityTypes.power,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [],
    effectsForMe: [],
    damage: 0,
    targetsCount: 0,
    heal: 0,
    reload: Infinity,
    chances: [],
  },
  artefactWheelKing: {
    id: String(),
    name: 'Штурвал Короля пиратов',
    description: 'Накладывает на выбранного противника слабость, он наносит на 5 ед. меньше урона',
    type: AbilityTypes.spell,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [Effects.weakness_5.id],
    effectsForMe: [],
    damage: 0,
    targetsCount: 1,
    heal: 0,
    reload: 5,
    chances: [],
  },
  swordBlack: {
    id: String(),
    name: 'Одноручный меч Черного мечника',
    description: 'Накладывает на выбранного противника слабость, он наносит на 5 ед. меньше урона',
    type: AbilityTypes.sword,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [],
    effectsForMe: [],
    damage: 10,
    targetsCount: 1,
    heal: 0,
    reload: 5,
    chances: [
      {
        effectsToTargets: [Effects.teamBleeding_2.id, Effects.bleeding_2.id],
        probability: 0.5,
      },
    ],
  },
  swordShadow: {
    id: String(),
    name: 'Удар клинками теней',
    description: 'Накладывает кровотечение 2, бъет сразу 2 цели',
    type: AbilityTypes.sword,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [Effects.bleeding_2.id],
    effectsForMe: [],
    damage: 5,
    targetsCount: 2,
    heal: 0,
    reload: 5,
    chances: [],
  },
  pistolFuture: {
    id: String(),
    name: 'Выстрел Пистоля будущего',
    description: 'Даёт огромный урон, но накладывает на выбранного противника силу 5',
    type: AbilityTypes.pistol,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [],
    effectsForMe: [],
    damage: 20,
    targetsCount: 1,
    heal: 0,
    reload: 5,
    chances: [],
  },
  swordZirael: {
    id: String(),
    name: 'Удар меча Зираэль',
    description: '',
    type: AbilityTypes.sword,
    imageUrl: DefaultAbilityImage,
    effectsToTargets: [],
    effectsForMe: [],
    damage: 10,
    targetsCount: 1,
    heal: 0,
    reload: 3,
    chances: [],
  },
};

// Set right id's
Object.keys(Abilities).forEach(id => {
  Abilities[id].id = String(id);
});
